# -*- coding: utf-8 -*-
"""Input

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlRWQIbeIfhiElHyXblTok_6nol9AH1-
"""

from eulerexplicit import *

def function(x,y):
  if y > 4000:
    return (42*x*np.exp(-0.273*x)) + 10*np.cos(2*np.pi*x) - 0.16*(y - 4000)**2
  else:
    return (42*x*np.exp(-0.273*x)) + 10*np.cos(2*np.pi*x)
x0 = 0
y0 = 3900
h = 0.01
xn = 10
printPlot = 1
printItr = 1
hvar = 0
Euler(function,x0,y0,h,xn,printPlot,printItr,hvar)

Inbuilt(function,10, 3900)